[package]
name = "spi-demo"
version = "0.1.0"
authors = ["Fredrik Simonsson <simson@thesimson.net>"]
edition = "2018"
publish = false

[dependencies]
cortex-m-rt = "0.7.0"
panic-halt = "0.2.0"
embedded-hal-spy = "0.0.5"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2"

[dependencies.nrf52832-hal]
path = "../../nrf52832-hal"
optional = true

[features]
52832 = ["nrf52832-hal"]
default = ["52832"]
